//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.09 at 02:59:55 PM WEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.openarchives.org/OAI/2.0/oai_dc/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.lyncode.oai.proxy.xml.oaidc;
