//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.12 at 12:07:10 AM WEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.lyncode.com/Repository/")
package com.lyncode.oai.proxy.xml.repository;
